name: New Branch Created

on:
  push:
    branches:
    - '*'
  create:
    tags:
    - '*'
jobs:
  Check-Branch-Name:
    runs-on: ubuntu-latest
    
    outputs:
      issue_num: ${{ steps.step1.outputs.issue_num }}
      tracked: ${{ steps.step1.outputs.tracked }}
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GHPROJECT_TOKEN }}
      - name: Get Created Issue Number
        id: step1
      
        run: |
          branch_name=`echo '${{github.event.ref}}'`
          issue_num=`echo ${branch_name#*#} | egrep -o '^[^/]+'`
          re='^[0-9]+$'
          if ! [[ $issue_num =~ $re ]] ; then
            echo "tracked=false" >> $GITHUB_OUTPUT
          else
            echo "tracked=true" >> $GITHUB_OUTPUT
          fi
            echo "issue_num=$issue_num" >> $GITHUB_OUTPUT
